#BSUB -J SFig29E_fhigh[3-1000]
#BSUB -W 3:01
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig29/errDir/SFig29E_fhigh_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig29/errDir/SFig29E_fhigh_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 3
#BSUB -R rusage[mem=3]

# run 1-1000
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig29/SFig29E_sim_high.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig29/errDir/SFig29E_fhigh_$LSB_JOBINDEX.out
