#BSUB -J summarizeS2[1-1]
#BSUB -W 1:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/test/errDir/summarize_ukb_S2_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/test/errDir/summarize_ukb_S2_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 32
#BSUB -R rusage[mem=32]

# run 1-9
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/test/csmGmm_reproduce/Fig4/summarize_ukb_analysis.R $LSB_JOBINDEX 2 >/rsrch3/home/biostatistics/rsun3/empBayes/test/errDir/summarize_ukb_S2_$LSB_JOBINDEX.out
