#BSUB -J mediation[1-15]
#BSUB -W 4:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/Fig4/errDir/analyze_med_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/Fig4/errDir/analyze_med_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 4
#BSUB -R rusage[mem=4]

# run 1-15
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/Fig4/mediation_analysis.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/Fig4/errDir/analyze_med_$LSB_JOBINDEX.out
