#BSUB -J sfig9dcombined[101-102]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig9/errDir/sfig9dcombined_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig9/errDir/sfig9dcombined_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 24
#BSUB -R rusage[mem=24]

# Run 1-800
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig9/SFig9D_sim_combined.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig9/errDir/sfig9dcombined_$LSB_JOBINDEX.out
