#BSUB -J sfig9akernel[101-102]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig9/errDir/sfig9acombined_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig9/errDir/sfig9acombined_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 4
#BSUB -R rusage[mem=4]

# Run 1-2000
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig9/SFig9A_sim_combined.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig9/errDir/sfig9akernel_$LSB_JOBINDEX.out
