#BSUB -J sfig11csmgmm[101-102]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig11/errDir/sfig11c_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig11/errDir/sfig11c_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 24
#BSUB -R rusage[mem=24]

# Run 1-2000
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig11/SFig11_sim_csmGmm.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig11/errDir/sfig11c_$LSB_JOBINDEX.out
