#BSUB -J SFig17B[1-300]
#BSUB -W 3:01
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig17/errDir/SFig17B_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig17/errDir/SFig17B_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 3
#BSUB -R rusage[mem=3]

# run 1-160
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig17/SuppFig17B_sim.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig17/errDir/SFig17B_$LSB_JOBINDEX.out
