#BSUB -J SFig17A[1-600]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig17/errDir/SFig17A_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig17/errDir/SFig17A_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 3
#BSUB -R rusage[mem=3]

# run 1-160
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig17/SuppFig17A_sim.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig17/errDir/SFig17A_$LSB_JOBINDEX.out
