#BSUB -J SFig14B[1-400]
#BSUB -W 3:01
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig14/errDir/SFig14B_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig14/errDir/SFig14B_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 4
#BSUB -R rusage[mem=4]

# run 1-400
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig14/SuppFig14B_sim.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig14/errDir/SFig14B_$LSB_JOBINDEX.out
