#BSUB -J S4A_S7[101-102]
#BSUB -W 7:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig4/errDir/SFig4A_S7_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig4/errDir/SFig4A_S7_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 4
#BSUB -R rusage[mem=4]

# run 221-600
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig4/SFig4A_power_correction.R $LSB_JOBINDEX 7 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig4/errDir/SFig4A_S7_$LSB_JOBINDEX.out
