#BSUB -J S4B_S5[1-160]
#BSUB -W 7:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig4/errDir/SFig4B_S5_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig4/errDir/SFig4B_S5_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 4
#BSUB -R rusage[mem=4]

# run 1-160
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig4/SFig4B_power_correction.R $LSB_JOBINDEX 5 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig4/errDir/SFig4B_S5_$LSB_JOBINDEX.out
