#BSUB -J sfig10bs2[101-102]
#BSUB -W 3:01
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig10/errDir/sfig10bs2_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig10/errDir/sfig10bs2_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 24
#BSUB -R rusage[mem=24]

# Run 1-2000
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig10/SFig10B_sim_combined.R $LSB_JOBINDEX 2 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig10/errDir/sfig10bs2_$LSB_JOBINDEX.out
