#BSUB -J sfig10as9[101-102]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig10/errDir/sfig10as9_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig10/errDir/sfig10as9_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 4
#BSUB -R rusage[mem=4]

# Run 1-2000
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig10/SFig10A_sim_combined.R $LSB_JOBINDEX 9 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig10/errDir/sfig10as9_$LSB_JOBINDEX.out
