#BSUB -J SFig26A_fr[101-102]
#BSUB -W 3:01
#BSUB -o /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig26/errDir/SFig26A_fr_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig26/errDir/SFig26A_fr_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/test/csmGmm_reproduce
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 3
#BSUB -R rusage[mem=3]

# run 1-400
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig26/SFig26A_sim_fitreg.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig26/errDir/SFig26A_fr_$LSB_JOBINDEX.out
