#BSUB -J analS10[1-2]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppTab2/errDir/analysisS10_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppTab2/errDir/analysisS10_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 16
#BSUB -R rusage[mem=16]

# run 1-400
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppTab2/analysis_timing.R $LSB_JOBINDEX 10 >/rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppTab2/errDir/analysisS10_$LSB_JOBINDEX.out
