#BSUB -J reptime[1-2]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppTab2/errDir/reptime_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppTab2/errDir/reptime_f1_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 3
#BSUB -R rusage[mem=3]

# run 1-100
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppTab2/Fig3D_timing.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppTab2/errDir/reptime_$LSB_JOBINDEX.out
