#BSUB -J analS14[3-100]
#BSUB -W 23:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppTab2/errDir/analysisS14_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppTab2/errDir/analysisS14_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 32 
#BSUB -R rusage[mem=32]

# run 1-400
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppTab2/analysis_timing.R $LSB_JOBINDEX 14 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppTab2/errDir/analysisS14_$LSB_JOBINDEX.out
