#BSUB -J Fig3A[501-502]
#BSUB -W 7:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig3/errDir/Fig3A_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig3/errDir/Fig3A_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q medium
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 4
#BSUB -R rusage[mem=4]

# run 221-620
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig3/Fig3A_sim.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig3/errDir/Fig3A_$LSB_JOBINDEX.out
