#BSUB -J leg3C[701-702]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig3/errDir/Fig3Cleg_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig3/errDir/Fig3Cleg_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 4
#BSUB -R rusage[mem=4]

# do 441-1241 of these
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig3/Fig3C_sim_legacy.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig3/errDir/Fig3Cleg_$LSB_JOBINDEX.out
