#BSUB -J SFig32A[1-400]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig32/errDir/SFig32A_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig32/errDir/SFig32A_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 3
#BSUB -R rusage[mem=3]

# run 1-400
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig32/SFig32A_sim.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/SuppFig32/errDir/SFig32A_$LSB_JOBINDEX.out
