#BSUB -J SFig25A_f4[101-102]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig25/errDir/SFig25A_f4_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig25/errDir/SFig25A_f4_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/test/csmGmm_reproduce
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 3
#BSUB -R rusage[mem=3]

# run 1-400
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig25/SFig25A_sim_fit4.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/test/csmGmm_reproduce/SuppFig25/errDir/SFig25A_f4_$LSB_JOBINDEX.out
