#BSUB -J Fig1D[301-302]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig1/errDir/Fig1D_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig1/errDir/Fig1D_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 3
#BSUB -R rusage[mem=3]

# Run 1-320
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig1/Fig1D_sim.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/empBayes/reproduce/Fig1/errDir/Fig1D_$LSB_JOBINDEX.out
