#BSUB -J Fig1C[701-702]
#BSUB -W 3:00
#BSUB -o /rsrch3/home/biostatistics/rsun3/empBayes/test/errDir/Fig1C_log%I.out
#BSUB -e /rsrch3/home/biostatistics/rsun3/empBayes/test/errDir/Fig1C_%I.err
#BSUB –cwd /rsrch3/home/biostatistics/rsun3/ukb/
#BSUB -q short
#BSUB -u rsun3@mdanderson.org
#BSUB -n 1
#BSUB -M 3
#BSUB -R rusage[mem=3]

# run 1-800
module load R/4.2.1
Rscript /rsrch3/home/biostatistics/rsun3/empBayes/test/csmGmm_reproduce/Fig1/Fig1C_sim.R $LSB_JOBINDEX 1 >/rsrch3/home/biostatistics/rsun3/empBayes/test/errDir/Fig1C_$LSB_JOBINDEX.out
